### PR TITLE
added dashboard

### PR DESCRIPTION
**Pull request by traore19**

### CODE REVIEW

**Comment by honorezemagho** [comment]
@elridge pleas review this pull request for the dashboard

**Comment by elridge** [comment]
> @elridge pleas review this pull request for the dashboard

You mentioned the wrong guy I guess. Did you mean to mention @eldrige?

**Comment by honorezemagho** [comment]
> > @elridge pleas review this pull request for the dashboard
> 
> You mentioned the wrong guy I guess. Did you mean to mention @eldrige?

Sorry for the inconvenience it was @eldrige

**Review by eldrige — APPROVED** [review]
Good Job, Fadi.
Keep up with your good work

**Pull request merged**
